---

version: '3.9'

services:
  webhookbot:
    image: atompi/webhookbot:v1.1.0
    restart: unless-stopped
    volumes:
      - ./webhookbot.yaml:/app/webhookbot.yaml
      - ./tmpl:/app/tmpl

networks:
  default:
    external: true
    name: nginx_proxy
